--INSERT INTO ORDERS (ticker, type, volume, price, currency) VALUES ('TSLA', 'SELL', 200, 150, 'USD');
--INSERT INTO ORDERS (ticker, type, volume, price, currency) VALUES ('TSLA', 'SELL', 180, 140, 'USD');
--INSERT INTO ORDERS (ticker, type, volume, price, currency) VALUES ('SAVE', 'BUY', 100, 25, 'SEK');